### ISSUE TITLE
[mtp-server] get access to phone file system

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#52]

**Comment by aleixpol** [comment]
Just researched a bit, I saw there's already an mtp server in our devices: https://launchpad.net/mtp
It doesn't start though, that's the error message, will need to look into it further:

phablet@ubuntu-phablet:~$ /usr/bin/mtp-server 
E0613 21:32:39.052184  2359 server.cpp:441] Could not start the MTP server:org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.UnityGreeter was not provided by any .service files

**Comment by star-buck** [comment]
cloned our own version: https://github.com/plasma-mobile/mtp-server

**Comment by star-buck** [comment]
@jriddell : 
replace mtp-server package with ods package from here: https://github.com/plasma-mobile/mtp-server

**Comment by vHanda** [comment]
The `mtp-server` command needs to be manually run.

    $ adb shell
    > $ export DISPLAY=:0
    > $ mtp-server

**Comment by jriddell** [comment]
mtp-server does not currently run as server/server.cpp requires unity greeter
"Could not start the MTP server:org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.UnityGreeter was not provided by any .service files"
also mtp-state is an upstart job to decide on whether it can start mtp-server and it needs env var persist.sys.usb.config=mtp which isn't currently set.  that needs either set or known that we can ignore it

**Comment by aleixpol** [comment]
The UnityGreeter error is what Vishesh was workarounding, AFAIU. Maybe you're not running his patch?

**Comment by jriddell** [comment]
mm yes.. investigating..

**Comment by jriddell** [comment]
mtp-server.conf simplified should work now, adding to rebuild queue..

**Comment by jriddell** [comment]
built

**Comment by star-buck** [comment]
doesnmt work as of 104

**Comment by star-buck** [comment]
v105: still not working

**Comment by star-buck** [comment]
107: package installed, but still not started:
The `mtp-server` command needs to be manually run.

    $ adb shell
    > $ export DISPLAY=:0
    > $ mtp-server

**Comment by star-buck** [comment]
works as of 109! :)
